name: Ruby

on:
  push:
    branches:
    - dev
    - master
  pull_request:
    branches: 
    - dev
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      API_TOKEN_GITHUB: ${{ secrets.BOT_GITHUB_KEY }}
      DANGER_GITHUB_API_TOKEN: ${{ secrets.BOT_GITHUB_KEY }}
      PR_NUMBER: ${{ github.event.number }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.2
        bundler-cache: true
    # Run specs
    - name: Run RSpec
      run: |
        bundle exec rspec
    - name: Push coverage report
      uses: kudocs/copy_file_to_another_repo_action@main
      with:
        source_file: 'coverage'
        destination_repo: 'kudocs/coverage'
        destination_folder: 'betteruptime/${{github.event.number || github.head_ref || github.ref_name }}'
        user_email: 'bot@kudocs.co.uk'
        user_name: 'kudocsbot'
        commit_message: 'Add ${{github.repository}} coverage report'
    # Run danger
    - name: Run Danger
      run: |
        bundle exec danger
